/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITF;

import java.util.ArrayList;
import Conexion.Conectar_Base;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author okami
 */
public class Buscar_pac extends javax.swing.JFrame {
    
    Conectar_Base con;
    Statement stm;
    ResultSet rst;
    String Atributo="DNI";
    /**
     * Creates new form Consultar_Paciente
     */
    public Buscar_pac() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrartabla("");
        txt_buscar.setEnabled(false);
        //Llenar();
    }
    void mostrartabla(String valor){
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("DNI");
        modelo.addColumn("NOMBRES");
        modelo.addColumn("APELLIDOS");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("SEGURIDAD_SOCIAL");
        modelo.addColumn("MUTUALIDAD");
        tbl_buscar_paciente.setModel(modelo);
        String sql="";
            if(valor.equals("")){
                sql="SELECT * FROM PACIENTES";
            }else{
                sql="SELECT * FROM PACIENTES WHERE "+Atributo+"='"+valor+"'";
            }
        String datos[] =new String[7];
        try{
            con= new Conectar_Base();
            stm=con.getConnection().createStatement();
            rst=stm.executeQuery(sql);
            while(rst.next()){
                datos[0]=rst.getString(1);
                datos[1]=rst.getString(2);
                datos[2]=rst.getString(3);
                datos[3]=rst.getString(4);
                datos[4]=String.valueOf(rst.getInt(5));
                datos[5]=rst.getString(6);
                datos[6]=rst.getString(7);
                modelo.addRow(datos);
            }
            tbl_buscar_paciente.setModel(modelo);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    /*public Vector ConsultaData(String valor){
        Vector registros=null;
        try{
            Connection cn;
            con= new Conectar_Base();
            stm=con.getConnection().createStatement();
            String sql="";
            if(valor.equals("")){
                sql="SELECT * FROM PACIENTES";
            }else{
                sql="SELECT * FROM PACIENTES WHERE "+Atributo+"='"+valor+"'";
            }
            rst=con.Listar(sql);
            ResultSet rs=stm.executeQuery(sql);
            registros=new Vector();
            while(rs.next()){
            Vector item=new Vector();
            item.add(rs.getString("DNI"));
            item.add(rs.getString("NOMBRES"));
            item.add(rs.getString("APELLIDOS"));
            item.add(rs.getString("DIRECCION"));
            item.add(rs.getInt("TELEFONO"));
            item.add(rs.getString("SEGURIDAD_SOCIAL"));
            item.add(rs.getString("MUTUALIDAD"));
            registros.add(item);
        }
            
        }catch(SQLException e){
        }
        return registros;
    }
    
    public void Llenar(){
        Vector columnas=new Vector();
        columnas.addElement("DNI");
        columnas.addElement("NOMBRES");
        columnas.addElement("APELLIDOS");
        columnas.addElement("DIRECCION");
        columnas.addElement("TELEFONO");
        columnas.addElement("SEGURIDAD_SOCIAL");
        columnas.addElement("MUTUALIDAD");
        Vector registros=new Vector();
        registros=ConsultaData("");
        DefaultTableModel dtm=new DefaultTableModel(registros,columnas);
        this.tbl_buscar_paciente.setModel(dtm);
    }/*
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_buscar_paciente = new javax.swing.JTable();
        btn_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("BUSCAR PACIENTE:");

        tbl_buscar_paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_buscar_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_buscar_pacienteMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_buscar_paciente);

        btn_aceptar.setBackground(new java.awt.Color(255, 255, 255));
        btn_aceptar.setForeground(new java.awt.Color(0, 0, 0));
        btn_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/habilitar_opt.png"))); // NOI18N
        btn_aceptar.setText("ACEPTAR");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_aceptar)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        dispose();
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void tbl_buscar_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_buscar_pacienteMousePressed
        int fila =tbl_buscar_paciente.getSelectedRow();
        try{
        this.txt_buscar.setText(tbl_buscar_paciente.getValueAt(fila, 0).toString());
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_tbl_buscar_pacienteMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            //jabtn_dning.Logger.getLogger(Consultar_Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar_pac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar_pac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar_pac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar_pac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_buscar_paciente;
    public static javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
