/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITF;
import java.util.ArrayList;
import Conexion.Conectar_Base;
import Datos.*;
import Procesos.*;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FRAME_ESPECIALIDAD extends javax.swing.JFrame {

    DefaultTableModel dtm;
    Conectar_Base con;
    CallableStatement cst;
    ResultSet rst;
    Statement stm;
    Especialidad esp =new Especialidad();
    P_Especialidad pesp=new P_Especialidad();
    int contador;
    int des_contador;
    
    
    public void Llenar(){
        Vector columnas=new Vector();
        columnas.addElement("ID_ESPECIALIDAD");
        columnas.addElement("NOMBRE DE ESPECIALIDAD");
        Vector registros=new Vector();
        registros=ConsultaData();
        DefaultTableModel dtm=new DefaultTableModel(registros,columnas);
        this.tbl_especialidad.setModel(dtm);
    }
    
    public Vector ConsultaData(){
        Vector registros=null;
        int conta=1;
        try{
            con= new Conectar_Base();
            stm=con.getConnection().createStatement();
            String sql="SELECT * FROM ESPECIALIDAD";
            rst=con.Listar(sql);
        ResultSet rs=stm.executeQuery(sql);
        registros=new Vector();
        while(rs.next()){
            Vector item=new Vector();
            item.add(rs.getInt("ID_ESPECIALIDAD"));
            item.add(rs.getString("NOMBRE_ESP"));
            conta++;
            contador=conta;
            registros.add(item);
        }
        }catch(SQLException e){
        }
        return registros;
    }
    
    public void Deshab_Llenar(){
        Vector columnas=new Vector();
        columnas.addElement("ID_ESPECIALIDAD");
        columnas.addElement("NOMBRE DE ESPECIALIDAD");
        Vector registros=new Vector();
        registros=Deshab_ConsultaData();
        DefaultTableModel dtm=new DefaultTableModel(registros,columnas);
        this.tbl_especialidad.setModel(dtm);
    }
    
    public Vector Deshab_ConsultaData(){
        Vector registros=null;
        int conta=0;
        try{
            con= new Conectar_Base();
            stm=con.getConnection().createStatement();
            String sql="SELECT * FROM DESHAB_ESP";
            rst=con.Listar(sql);
        ResultSet rs=stm.executeQuery(sql);
        registros=new Vector();
        while(rs.next()){
            Vector item=new Vector();
            item.add(rs.getInt("DS_ID_ESPECIALIDAD"));
            item.add(rs.getString("DS_NOMBRE_ESP"));
            conta++;
            des_contador=conta;
            registros.add(item);
        }
        }catch(SQLException e){
        }
        return registros;
    }
    
    
    public void Limpiar(){
        txt_codigo.setText("");
        txt_especilidad.setText("");
    }
    
    public void TXT_OPEN(){
        //txt_codigo.setEnabled(true);
        txt_especilidad.setEnabled(true);
        btn_deshabilitar.setEnabled(true);
        btn_habilitar.setEnabled(true);
        btn_guardar.setEnabled(true);
    }
    
    public void TXT_CLOSE(){
        txt_codigo.setEnabled(false);
        txt_especilidad.setEnabled(false);
        btn_deshabilitar.setEnabled(false);
        btn_habilitar.setEnabled(false);
        btn_guardar.setEnabled(false);
    }
    
    public void Genera_cod(){
        int resul=contador+des_contador;
        txt_codigo.setText(String.valueOf(resul));
    }
    
    public FRAME_ESPECIALIDAD() {
        initComponents();
        this.setLocationRelativeTo(null);
        Llenar();
        TXT_CLOSE();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_especilidad = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        btn_deshabilitar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_especialidad = new javax.swing.JTable();
        btn_nuevo = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_mostrar = new javax.swing.JButton();
        btn_habilitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ESPECIALIDAD");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CODIGO:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("ESPECIALIDAD:");

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/guardar_24.png"))); // NOI18N
        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_deshabilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/delete_nel.png"))); // NOI18N
        btn_deshabilitar.setText("DESHABILITAR");
        btn_deshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deshabilitarActionPerformed(evt);
            }
        });

        tbl_especialidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_especialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_especialidadMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_especialidad);

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/new.png"))); // NOI18N
        btn_nuevo.setText("NUEVO");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/UPDATE.png"))); // NOI18N
        btn_actualizar.setText("ACTUALIZAR");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/mostrar_men.png"))); // NOI18N
        btn_mostrar.setText("MOSTRAR");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });

        btn_habilitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/habilitar_opt.png"))); // NOI18N
        btn_habilitar.setText("HABILITAR");
        btn_habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_habilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_especilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btn_nuevo)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_actualizar)
                            .addComponent(btn_guardar))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_deshabilitar)
                                .addGap(30, 30, 30)
                                .addComponent(btn_habilitar))
                            .addComponent(btn_mostrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_especilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_nuevo)
                    .addComponent(btn_deshabilitar)
                    .addComponent(btn_habilitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_mostrar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
         if(this.txt_codigo.getText().equals("")){
            JOptionPane.showMessageDialog(null,"FALTA ESCRIBIR EL CODIGO ","VERIFICAR",JOptionPane.WARNING_MESSAGE);
            this.txt_codigo.requestFocus();
        }else if(this.txt_especilidad.getText().equals("")){
            JOptionPane.showMessageDialog(null, "FALTA ESCRIBIR NOMBRE");
            this.txt_especilidad.requestFocus();
        }
          try{
            esp.setIDESPECIALIDAD(Integer.parseInt(txt_codigo.getText()));
            esp.setNOMBRE_ESP(txt_especilidad.getText());
            pesp.Insertar(esp);
            Limpiar();
            JOptionPane.showMessageDialog(null, "DATOS INGRESADOS");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "DATOS NO INGRESADOS");
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        Llenar();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_deshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deshabilitarActionPerformed
       try{
            esp.setIDESPECIALIDAD(Integer.parseInt(txt_codigo.getText()));
            esp.setNOMBRE_ESP(txt_especilidad.getText());
            pesp.Deshabilitar(esp);
            Limpiar();
            JOptionPane.showMessageDialog(null, "DATOS DESHABILITADOS");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "DATOS NO DESHABILITADOS");
        }
    }//GEN-LAST:event_btn_deshabilitarActionPerformed

    private void btn_habilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_habilitarActionPerformed
        try{
            esp.setIDESPECIALIDAD(Integer.parseInt(txt_codigo.getText()));
            esp.setNOMBRE_ESP(txt_especilidad.getText());
            pesp.Habilitar(esp);
            pesp.Limpiar_Deshab(esp);
            Limpiar();
            JOptionPane.showMessageDialog(null, "DATOS HABILITADOS");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "DATOS NO HABILITADOS");
        }
    }//GEN-LAST:event_btn_habilitarActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
    Deshab_Llenar();
    }//GEN-LAST:event_btn_mostrarActionPerformed

    private void tbl_especialidadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_especialidadMousePressed
       int fila = tbl_especialidad.getSelectedRow();
        Limpiar();
        /*TXT_HABILITADO();
        txt_dni.setEnabled(false);
        btn_guardar.setEnabled(false);
        btn_habilitar.setEnabled(true);
        btn_deshabilitar.setEnabled(true);
        btn_modificar.setEnabled(true);*/
        try{
        this.txt_codigo.setText(tbl_especialidad.getValueAt(fila, 0).toString());
        this.txt_especilidad.setText(tbl_especialidad.getValueAt(fila, 1).toString());
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_tbl_especialidadMousePressed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        TXT_OPEN();
        Genera_cod();
        
    }//GEN-LAST:event_btn_nuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRAME_ESPECIALIDAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRAME_ESPECIALIDAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRAME_ESPECIALIDAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRAME_ESPECIALIDAD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRAME_ESPECIALIDAD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_deshabilitar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_habilitar;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_especialidad;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_especilidad;
    // End of variables declaration//GEN-END:variables
}
